apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-go-app
  name: go-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-go-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-go-app
    spec:
      containers:
        - image: db-client:latest
          name: db-client
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: APP_PORT
              value: "8080"